# Generated by Django 2.2.1 on 2019-05-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma_rc', models.CharField(max_length=45)),
                ('lemma_utf', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_key', models.CharField(max_length=45)),
                ('token_rc', models.CharField(max_length=45)),
                ('token_utf', models.CharField(max_length=45)),
                ('flex_type', models.CharField(max_length=45)),
                ('gram', models.CharField(max_length=45)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Lemma')),
            ],
        ),
    ]
