# Generated by Django 2.2.1 on 2019-05-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0002_token_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='part_of_speech',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
