# Generated by Django 2.2.1 on 2019-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0003_auto_20190513_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='flex_type',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='gram',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_utf',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
