# Generated by Django 2.2.1 on 2019-05-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0004_auto_20190513_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('name_long', models.CharField(default=None, max_length=45, null=True)),
                ('encoding', models.CharField(default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('load_script', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='lemma_rc',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='lemma_utf',
        ),
        migrations.RemoveField(
            model_name='token',
            name='flex_type',
        ),
        migrations.RemoveField(
            model_name='token',
            name='gram',
        ),
        migrations.RemoveField(
            model_name='token',
            name='part_of_speech',
        ),
        migrations.RemoveField(
            model_name='token',
            name='sort_key',
        ),
        migrations.RemoveField(
            model_name='token',
            name='token_rc',
        ),
        migrations.RemoveField(
            model_name='token',
            name='token_utf',
        ),
        migrations.AddField(
            model_name='lemma',
            name='grammar_attributes',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='txt',
            field=models.CharField(default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='grammar_attributes',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='txt',
            field=models.CharField(default=None, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='lemma',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Lemma'),
        ),
        migrations.AddIndex(
            model_name='lemma',
            index=models.Index(fields=['txt'], name='rc_dic_lemm_txt_71e2de_idx'),
        ),
        migrations.AddField(
            model_name='paradigm',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Language'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Language'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='paradigm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Paradigm'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Source'),
        ),
        migrations.AddField(
            model_name='token',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Language'),
        ),
        migrations.AddField(
            model_name='token',
            name='paradigm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rc_dic.Paradigm'),
        ),
    ]
