# Generated by Django 2.2.7 on 2019-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0005_auto_20191108_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('name', 'encoding')},
        ),
    ]
