# Generated by Django 2.2.1 on 2019-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0006_auto_20190524_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name_long',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AddIndex(
            model_name='paradigm',
            index=models.Index(fields=['name'], name='rc_dic_para_name_19c290_idx'),
        ),
    ]
