# Generated by Django 2.2.1 on 2019-05-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0007_auto_20190524_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='paradigm',
        ),
        migrations.AddField(
            model_name='token',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Source'),
        ),
    ]
