# Generated by Django 2.2.7 on 2019-11-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rc_dic', '0005_auto_20191108_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128, unique=True)),
                ('name_long', models.CharField(default=None, max_length=45, null=True)),
                ('path', models.FilePathField(path='../source_data/ponomar')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('title_latin', models.CharField(default=None, max_length=64, null=True)),
                ('publisher', models.CharField(default=None, max_length=64, null=True)),
                ('year', models.IntegerField(default=None, null=True)),
                ('note', models.TextField(default=None, null=True)),
                ('path', models.FilePathField(default=None, null=True, path='../source_data/ponomar')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Language')),
            ],
        ),
    ]
