# Generated by Django 2.2.7 on 2019-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponomar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='key',
        ),
        migrations.RemoveField(
            model_name='book',
            name='note',
        ),
        migrations.RemoveField(
            model_name='book',
            name='path',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_latin',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_long',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
