# Generated by Django 2.2.7 on 2019-11-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponomar', '0002_auto_20191108_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_long',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
