# Generated by Django 2.2.7 on 2019-11-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rc_dic', '0005_auto_20191108_1901'),
        ('ponomar', '0003_auto_20191108_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_long', models.CharField(default=None, max_length=128, null=True)),
                ('path', models.CharField(default=None, max_length=256, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponomar.Book')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rc_dic.Language')),
            ],
        ),
    ]
