# Generated by Django 2.2.7 on 2019-11-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponomar', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(default=None, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponomar.Chapter')),
            ],
        ),
    ]
