# Generated by Django 2.2.7 on 2019-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponomar', '0005_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='txt',
            new_name='txt_plain',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='txt_raw',
            field=models.TextField(default=None, null=True),
        ),
    ]
