# Generated by Django 2.2.7 on 2019-11-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponomar', '0006_auto_20191109_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='txt_plain',
        ),
    ]
